name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install project (dev)
        run: |
          python -m pip install -e ".[dev]"

      - name: Lint
        run: |
          python -m ruff check .

      - name: Test
        run: |
          python -m pytest -q
